#!/bin/bash

echo "USING: ${DABUSR}/etc/profile_local_extra"

if [ $CONFIG ] ; then
# 	echo  "INFO: CONFIG is ${CONFIG} "
        export MAYA_SCRIPT_PATH="${CONFIG}/mayaConfig/scripts_common:${MAYA_SCRIPT_PATH}"
        export MAYA_PLUG_IN_PATH="${CONFIG}/mayaConfig/plug-ins_common:${MAYA_PLUG_IN_PATH}"
        export MAYA_APP_DIR="${CONFIG}/mayaConfig"
        export MAYA_MODULE_PATH="${CONFIG}/mayaConfig/modules_common:${MAYA_MODULE_PATH}"
        export XBMLANGPATH="${CONFIG}/mayaConfig/icons_common/\%B":${XBMLANGPATH}
        export MAYA_SHELF_PATH="${CONFIG}/mayaConfig/shelves_common:${MAYA_SHELF_PATH}"
else
	echo  "WARNING: CONFIG not found still "
fi


