#!/usr/bin/python

import sys, json

if __name__=="__main__":
    # determine selected tasks
    jsonData = sys.stdin.read()
    if jsonData:
        tasks = json.loads(jsonData)

    # something could be done to determine which image to return
    # for now just return a test image in /tmp of the engine host
    filename = "/tmp/image.jpg"

    # return the image; it will be displayed in a new browser window
    with open(filename, "rb") as content_file:
        content = content_file.read()
    #sys.stdout.write("Content-type: image/jpg\n\n")
    sys.stdout.write("Content-type: image/jpg")
    sys.stdout.write(content)

